serverconf:
  name: develpoment
  SERVICE_USER_PORT : :7001
databaseconf:
  driver: postgres
  username: root
  password: 12345678
  port: 37892
  dbname: postgres
  address: localhost
  schemas: public